// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config"; // Ez legyen az ELSŐ sor!
import { defineConfig } from "@prisma/config";

// Kézi ellenőrzés a konzolon (opcionális, de segít a hibakeresésben)
if (!process.env.DATABASE_URL) {
  console.warn("FIGYELEM: A DATABASE_URL nincs beállítva a környezeti változók között!");
}

export default defineConfig({
  schema: "prisma/schema.prisma",
  datasource: {
    url: process.env.DATABASE_URL, 
  },
});